version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  server:
    build: .
    volumes:
      - ./api:/code/api
      - ./{{ cookiecutter.project_name }}:/code/{{ cookiecutter.project_name }}
    ports:
      - "80:8000"
    command: sh ./scripts/run.sh
    env_file:
     - ./.env
    links:
      - db
    depends_on:
      - db
    