[default]
SECRET_KEY = "default"

[development]
DEBUG = "True"

[development.DATABASES.default]
ENGINE = "django.db.backends.sqlite3"
NAME = "db.sqlite3"

[production]
DEBUG = "False"

[production.DATABASES.default]
ENGINE = "django.db.backends.postgresql_psycopg2"
NAME = "postgres"
USER = "postgres"
HOST = "db"
PORT = 5432
PASSWORD = "postgres"